"""Version 0.1 mathematical core for a 4-axis filament winder."""

from filament_winder.core.coverage import CoverageMap, CoverageSummary, cylinder_coverage_map
from filament_winder.core.geometry import CylinderMandrel
from filament_winder.core.kinematics import (
    FeedrateConfig,
    FeedSchedule,
    MachineMotionTable,
    machine_path_from_surface_path,
    plan_feedrate,
)
from filament_winder.core.path_planning import (
    CylinderPatternCandidate,
    CylinderPatternOptimizationRequest,
    CylinderPatternOptimizationResult,
    ProfileDomePathConfig,
    ProfileDomePathGenerator,
    HelicalPathConfig,
    HelicalPathGenerator,
    PatternClosureEstimate,
    PlannedLayer,
    PlannedWindingProgram,
    ProfileHelicalPathConfig,
    ProfileHelicalPathGenerator,
    ProfileSafeZone,
    ProfileTurnaroundPathConfig,
    ProfileTurnaroundPathGenerator,
    SurfacePath,
    WindingLayerSpec,
    WindingPatternReport,
    WindingPointMetadata,
    WindingSchedule,
    axisymmetric_surface_coverage_map,
    estimate_cylinder_pattern_closure,
    find_profile_safe_zone,
    optimize_cylinder_pattern,
    plan_winding_schedule,
    validate_winding_program,
)
from filament_winder.core.tow import TowBand, generate_cylinder_tow_band
from filament_winder.core.validation import (
    AxisLimitConfig,
    NoGoZone,
    ValidationIssue,
    ValidationReport,
    validate_motion_table,
)

__all__ = [
    "CoverageMap",
    "CoverageSummary",
    "CylinderPatternCandidate",
    "CylinderPatternOptimizationRequest",
    "CylinderPatternOptimizationResult",
    "CylinderMandrel",
    "ProfileDomePathConfig",
    "ProfileDomePathGenerator",
    "HelicalPathConfig",
    "HelicalPathGenerator",
    "FeedSchedule",
    "FeedrateConfig",
    "MachineMotionTable",
    "NoGoZone",
    "PatternClosureEstimate",
    "ProfileHelicalPathConfig",
    "ProfileHelicalPathGenerator",
    "ProfileSafeZone",
    "ProfileTurnaroundPathConfig",
    "ProfileTurnaroundPathGenerator",
    "PlannedLayer",
    "PlannedWindingProgram",
    "SurfacePath",
    "WindingLayerSpec",
    "WindingPatternReport",
    "WindingPointMetadata",
    "WindingSchedule",
    "TowBand",
    "ValidationIssue",
    "ValidationReport",
    "AxisLimitConfig",
    "axisymmetric_surface_coverage_map",
    "cylinder_coverage_map",
    "estimate_cylinder_pattern_closure",
    "find_profile_safe_zone",
    "generate_cylinder_tow_band",
    "machine_path_from_surface_path",
    "optimize_cylinder_pattern",
    "plan_feedrate",
    "plan_winding_schedule",
    "validate_motion_table",
    "validate_winding_program",
]

__version__ = "0.1.0"
