from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
import pytest

from filament_winder.core.geometry import AxisymmetricProfileMandrel, CylinderMandrel
from filament_winder.core.kinematics import MachineMotionTable, machine_path_from_surface_path
from filament_winder.core.path_planning import (
    HelicalPathConfig,
    HelicalPathGenerator,
    ProfileHelicalPathConfig,
    ProfileHelicalPathGenerator,
    SurfacePath,
)
from filament_winder.core.tow import generate_cylinder_tow_band
from filament_winder.io import (
    GCodeOptions,
    export_cylinder_preview_obj,
    export_gcode,
    import_dxf_zr_profile,
)
from filament_winder.project import (
    CylinderMandrelConfig,
    MachineConfig,
    OutputConfig,
    WindingConfig,
    WindingProject,
    load_project,
    save_project,
)


def _generate_program() -> tuple[CylinderMandrel, SurfacePath, MachineMotionTable]:
    mandrel = CylinderMandrel(length_mm=100.0, radius_mm=20.0)
    config = HelicalPathConfig(winding_angle_deg=45.0, tow_width_mm=3.0, point_count=5)
    path = HelicalPathGenerator(mandrel, config).generate()
    motion = machine_path_from_surface_path(path, radial_clearance_mm=5.0)
    return mandrel, path, motion


def test_gcode_export_uses_grbl_style_four_axis_moves(tmp_path: Path) -> None:
    _, _, motion = _generate_program()

    output_path = export_gcode(
        motion,
        tmp_path / "path.gcode",
        options=GCodeOptions(feedrate_mm_min=750.0),
    )

    lines = output_path.read_text(encoding="utf-8").splitlines()
    assert lines[:4] == ["; Generated by FilamentWinder", "; Units: mm and degrees", "G21", "G90"]
    assert lines[4] == "G1 Z0.0000 A0.0000 X25.0000 B45.0000 F750.000"
    assert lines[-1] == "M2"


def test_obj_preview_export_includes_mandrel_path_and_tow_band(tmp_path: Path) -> None:
    mandrel, path, _ = _generate_program()
    tow_band = generate_cylinder_tow_band(mandrel, path)

    output_path = export_cylinder_preview_obj(
        mandrel,
        path,
        tmp_path / "preview.obj",
        tow_band=tow_band,
        theta_segments=8,
        z_segments=2,
    )

    text = output_path.read_text(encoding="utf-8")
    assert "o mandrel" in text
    assert "o helical_path" in text
    assert "o tow_band" in text
    assert "\nl " in text


def test_project_file_round_trip(tmp_path: Path) -> None:
    project = WindingProject(
        name="Test winding",
        mandrel=CylinderMandrelConfig(length_mm=1000.0, radius_mm=100.0),
        winding=WindingConfig(tow_width_mm=6.0, winding_angle_deg=45.0, point_count=500),
        machine=MachineConfig(radial_clearance_mm=25.0, feedrate_mm_min=500.0),
        outputs=OutputConfig(
            csv_path="exports/path.csv",
            gcode_path="exports/path.gcode",
            coverage_csv_path="exports/coverage.csv",
            preview_obj_path="exports/path.obj",
        ),
    )

    output_path = save_project(project, tmp_path / "project.fwp.json")
    loaded = load_project(output_path)

    assert loaded == project


def test_v1_project_file_loads_with_default_profile_and_pattern(tmp_path: Path) -> None:
    project_path = tmp_path / "legacy_project.fwp.json"
    project_path.write_text(
        """
{
  "name": "Legacy winding",
  "mandrel": {"length_mm": 1000.0, "radius_mm": 100.0},
  "winding": {
    "tow_width_mm": 6.0,
    "winding_angle_deg": 45.0,
    "point_count": 500,
    "passes": 1,
    "phase_offset_deg": null,
    "alternate_direction": true
  },
  "machine": {"radial_clearance_mm": 25.0, "feedrate_mm_min": 500.0},
  "outputs": {"csv_path": "exports/path.csv"},
  "schema_version": 1,
  "project_type": "filament_winder"
}
""".strip(),
        encoding="utf-8",
    )

    loaded = load_project(project_path)

    assert loaded.schema_version == 3
    assert loaded.profile.path_mode == "dome"
    assert not loaded.pattern.enabled
    assert loaded.ui.preview_mode == "cylinder"


def test_ascii_dxf_lwpolyline_imports_zr_profile(tmp_path: Path) -> None:
    dxf_path = tmp_path / "profile.dxf"
    dxf_tags: list[Any] = [
        "0",
        "SECTION",
        "2",
        "ENTITIES",
        "0",
        "LWPOLYLINE",
        "90",
        "3",
        "10",
        "0",
        "20",
        "0",
        "10",
        "50",
        "20",
        "20",
        "10",
        "100",
        "20",
        "10",
        "0",
        "ENDSEC",
        "0",
        "EOF",
    ]
    dxf_path.write_text("\n".join(str(tag) for tag in dxf_tags), encoding="utf-8")

    profile = import_dxf_zr_profile(dxf_path)

    assert profile.z_mm.tolist() == [0.0, 50.0, 100.0]
    assert profile.r_mm.tolist() == [0.0, 20.0, 10.0]
    assert profile.radius_at([75.0])[0] == pytest.approx(15.0)


def test_ascii_dxf_import_prefers_upper_profile_layer(tmp_path: Path) -> None:
    dxf_path = tmp_path / "closed_profile.dxf"
    dxf_path.write_text(
        "\n".join(
            [
                "0",
                "SECTION",
                "2",
                "ENTITIES",
                "0",
                "LWPOLYLINE",
                "8",
                "LOWER_PROFILE",
                "90",
                "3",
                "10",
                "0",
                "20",
                "0",
                "10",
                "50",
                "20",
                "-20",
                "10",
                "100",
                "20",
                "0",
                "0",
                "LWPOLYLINE",
                "8",
                "UPPER_PROFILE",
                "90",
                "3",
                "10",
                "0",
                "20",
                "0",
                "10",
                "50",
                "20",
                "20",
                "10",
                "100",
                "20",
                "0",
                "0",
                "LINE",
                "8",
                "CENTERLINE",
                "10",
                "0",
                "20",
                "0",
                "11",
                "100",
                "21",
                "0",
                "0",
                "ENDSEC",
                "0",
                "EOF",
            ]
        ),
        encoding="utf-8",
    )

    profile = import_dxf_zr_profile(dxf_path)

    assert profile.z_mm.tolist() == [0.0, 50.0, 100.0]
    assert profile.r_mm.tolist() == [0.0, 20.0, 0.0]


def test_generated_elliptical_dome_profile_imports() -> None:
    profile_path = Path(__file__).parents[1] / "mandrels" / (
        "2000mm_8in_od_elliptical_dome_profile.dxf"
    )

    profile = import_dxf_zr_profile(profile_path)

    assert profile.z_mm.size == 41
    assert profile.start_z_mm == pytest.approx(0.0)
    assert profile.end_z_mm == pytest.approx(2000.0)
    assert profile.max_radius_mm == pytest.approx(101.6)


def test_profile_helical_path_uses_local_radius_and_surface_slope() -> None:
    profile = AxisymmetricProfileMandrel(
        z_mm=np.asarray([0.0, 50.0, 100.0]),
        r_mm=np.asarray([20.0, 30.0, 20.0]),
    )
    config = ProfileHelicalPathConfig(
        winding_angle_deg=35.0,
        tow_width_mm=3.0,
        point_count=25,
        min_radius_mm=10.0,
    )

    path = ProfileHelicalPathGenerator(profile, config).generate()

    assert path.point_count == 25
    assert path.z_mm[0] == pytest.approx(0.0)
    assert path.z_mm[-1] == pytest.approx(100.0)
    assert path.theta_rad[-1] > 0.0
