"""G-code exporters and post-processors."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from filament_winder.core.feedrate import FeedSchedule
from filament_winder.core.kinematics import MachineMotionTable


@dataclass(frozen=True, slots=True)
class GCodeOptions:
    feedrate_mm_min: float = 500.0
    decimals: int = 4
    feed_schedule: FeedSchedule | None = None

    def __post_init__(self) -> None:
        if not np.isfinite(self.feedrate_mm_min) or self.feedrate_mm_min <= 0.0:
            raise ValueError("feedrate_mm_min must be a positive finite value")
        if self.decimals < 0:
            raise ValueError("decimals must be non-negative")


class BasePostProcessor:
    """Base interface for converting motion tables into controller text."""

    name = "base"

    def format_program(
        self,
        motion_table: MachineMotionTable,
        options: GCodeOptions | None = None,
    ) -> list[str]:
        raise NotImplementedError


class GRBLPostProcessor(BasePostProcessor):
    """Initial GRBL-style 4-axis post-processor."""

    name = "grbl"

    def format_program(
        self,
        motion_table: MachineMotionTable,
        options: GCodeOptions | None = None,
    ) -> list[str]:
        resolved_options = GCodeOptions() if options is None else options
        decimals = resolved_options.decimals
        lines = [
            "; Generated by FilamentWinder",
            "; Units: mm and degrees",
            "G21",
            "G90",
        ]
        feed_schedule = resolved_options.feed_schedule
        if feed_schedule is not None and feed_schedule.point_count != motion_table.point_count:
            raise ValueError("feed schedule must have the same point count as the motion table")
        for index in range(motion_table.point_count):
            feedrate = (
                resolved_options.feedrate_mm_min
                if feed_schedule is None
                else feed_schedule.feedrate_mm_min[index]
            )
            lines.append(
                "G1 "
                f"Z{motion_table.z_mm[index]:.{decimals}f} "
                f"A{motion_table.a_deg[index]:.{decimals}f} "
                f"X{motion_table.x_mm[index]:.{decimals}f} "
                f"B{motion_table.b_deg[index]:.{decimals}f} "
                f"F{feedrate:.3f}"
            )
        lines.append("M2")
        return lines


def export_gcode(
    motion_table: MachineMotionTable,
    output_path: str | Path,
    *,
    post_processor: BasePostProcessor | None = None,
    options: GCodeOptions | None = None,
) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    processor = GRBLPostProcessor() if post_processor is None else post_processor
    lines = processor.format_program(motion_table, options)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
        handle.write("\n")
    return path
