"""Surface path planning."""

from filament_winder.core.path_planning.geodesic import (
    AxisymmetricPathDiagnostics,
    ControlledAnglePathConfig,
    GeodesicPathConfig,
    generate_controlled_angle_path,
    generate_geodesic_path,
)
from filament_winder.core.path_planning.helical import (
    HelicalPathConfig,
    HelicalPathGenerator,
    PatternClosureEstimate,
    SurfacePath,
    estimate_cylinder_pattern_closure,
)
from filament_winder.core.path_planning.optimization import (
    CylinderPatternCandidate,
    CylinderPatternOptimizationRequest,
    CylinderPatternOptimizationResult,
    optimize_cylinder_pattern,
)
from filament_winder.core.path_planning.profile import (
    ProfileDomePathConfig,
    ProfileDomePathGenerator,
    ProfileHelicalPathConfig,
    ProfileHelicalPathGenerator,
    ProfileSafeZone,
    ProfileTurnaroundPathConfig,
    ProfileTurnaroundPathGenerator,
    find_profile_safe_zone,
)
from filament_winder.core.path_planning.schedule import (
    PlannedLayer,
    PlannedWindingProgram,
    WindingLayerSpec,
    WindingPatternReport,
    WindingPointMetadata,
    WindingSchedule,
    axisymmetric_surface_coverage_map,
    plan_winding_schedule,
    validate_winding_program,
)
from filament_winder.core.path_planning.segments import (
    PathSegment,
    PathState,
    build_path_segments,
    segment_labels_for_points,
)
from filament_winder.core.path_planning.textbook_patterns import (
    MultiLayerPatternResult,
    PatternSearchRequest,
    PatternSelectionResult,
    ThicknessDistribution,
    WindingPatternCandidate,
    effective_roving_width_mm,
    estimate_thickness_distribution,
    export_pattern_candidates_json,
    export_pattern_rejection_report_json,
    export_selected_pattern_json,
    export_thickness_distribution_csv,
    required_number_of_windings,
    select_winding_pattern,
)

__all__ = [
    "HelicalPathConfig",
    "HelicalPathGenerator",
    "AxisymmetricPathDiagnostics",
    "ControlledAnglePathConfig",
    "GeodesicPathConfig",
    "PatternClosureEstimate",
    "PathSegment",
    "PathState",
    "CylinderPatternCandidate",
    "CylinderPatternOptimizationRequest",
    "CylinderPatternOptimizationResult",
    "ProfileDomePathConfig",
    "ProfileDomePathGenerator",
    "ProfileHelicalPathConfig",
    "ProfileHelicalPathGenerator",
    "ProfileSafeZone",
    "ProfileTurnaroundPathConfig",
    "ProfileTurnaroundPathGenerator",
    "PlannedLayer",
    "PlannedWindingProgram",
    "SurfacePath",
    "WindingLayerSpec",
    "WindingPatternReport",
    "WindingPointMetadata",
    "WindingSchedule",
    "MultiLayerPatternResult",
    "PatternSearchRequest",
    "PatternSelectionResult",
    "ThicknessDistribution",
    "WindingPatternCandidate",
    "axisymmetric_surface_coverage_map",
    "build_path_segments",
    "effective_roving_width_mm",
    "estimate_thickness_distribution",
    "estimate_cylinder_pattern_closure",
    "export_pattern_candidates_json",
    "export_pattern_rejection_report_json",
    "export_selected_pattern_json",
    "export_thickness_distribution_csv",
    "find_profile_safe_zone",
    "generate_controlled_angle_path",
    "generate_geodesic_path",
    "optimize_cylinder_pattern",
    "plan_winding_schedule",
    "required_number_of_windings",
    "select_winding_pattern",
    "segment_labels_for_points",
    "validate_winding_program",
]
